<?php

namespace Database\Seeders;

use App\Models\PredefinedService;
use Illuminate\Database\Seeder;

class PredefinedServiceSeeder extends Seeder
{
    /**
     * Seeder basé sur les vraies données de GEST'IMMO
     * Sources: grille tarifaire, plaquette commerciale et tableau des missions
     */
    public function run(): void
    {
        $services = [
            // =====================================
            // MISE EN LOCATION (10€/m²)
            // =====================================
            [
                'name' => 'Estimation du loyer',
                'description' => 'Analyse du marché local et fixation du loyer optimal',
                'category' => 'location',
                'default_price' => 150.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 10,
            ],
            [
                'name' => 'Vérification des diagnostics',
                'description' => 'Contrôle des DPE, électricité, gaz, ERP avant location',
                'category' => 'location',
                'default_price' => 100.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 20,
            ],
            [
                'name' => 'Prise de photos du bien',
                'description' => 'Réalisation de photos professionnelles pour l\'annonce',
                'category' => 'location',
                'default_price' => 150.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 30,
            ],
            [
                'name' => 'Publication de l\'annonce',
                'description' => 'Diffusion sur portails immobiliers et site de l\'agence',
                'category' => 'location',
                'default_price' => 150.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 40,
            ],
            [
                'name' => 'Organisation des visites',
                'description' => 'Planification et accompagnement des visites sur site',
                'category' => 'location',
                'default_price' => 60.00,
                'default_tva_rate' => 20,
                'unit' => 'heure',
                'default_quantity' => 1,
                'sort_order' => 50,
            ],
            [
                'name' => 'Vérification de solvabilité',
                'description' => 'Étude des justificatifs de revenus et garants',
                'category' => 'location',
                'default_price' => 80.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 60,
            ],
            [
                'name' => 'Rédaction du bail vide',
                'description' => 'Rédaction conforme à la législation en vigueur',
                'category' => 'location',
                'default_price' => 100.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 70,
            ],
            [
                'name' => 'Rédaction du bail meublé',
                'description' => 'Rédaction conforme à la législation en vigueur',
                'category' => 'location',
                'default_price' => 130.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 80,
            ],
            [
                'name' => 'Mise en location - Prix au m²',
                'description' => 'Forfait global de mise en location (diffusion, visites, sélection candidats, étude solvabilité)',
                'category' => 'location',
                'default_price' => 10.00,
                'default_tva_rate' => 20,
                'unit' => 'm²',
                'default_quantity' => 1,
                'sort_order' => 5,
            ],

            // =====================================
            // GESTION LOCATIVE (5% des loyers)
            // =====================================
            [
                'name' => 'Émission des quittances',
                'description' => 'Création et envoi des quittances mensuelles',
                'category' => 'gestion',
                'default_price' => 20.00,
                'default_tva_rate' => 20,
                'unit' => 'mois',
                'default_quantity' => 1,
                'sort_order' => 300,
            ],
            [
                'name' => 'Relance pour impayé (1ère relance)',
                'description' => 'Envoi d\'un rappel au locataire par LRAR',
                'category' => 'gestion',
                'default_price' => 200.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 310,
            ],
            [
                'name' => 'Relance téléphonique (2e relance)',
                'description' => 'Pour impayé persistant',
                'category' => 'gestion',
                'default_price' => 150.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 320,
            ],
            [
                'name' => 'Mise en demeure pour impayé',
                'description' => 'Rédaction et envoi d\'une mise en demeure officielle',
                'category' => 'gestion',
                'default_price' => 350.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 330,
            ],
            [
                'name' => 'Suivi contentieux',
                'description' => 'Transmission au service juridique ou huissier',
                'category' => 'gestion',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 340,
            ],
            [
                'name' => 'Régularisation des charges',
                'description' => 'Calcul et refacturation annuelle des charges réelles',
                'category' => 'gestion',
                'default_price' => 150.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 350,
            ],
            [
                'name' => 'Révision annuelle du loyer',
                'description' => 'Application de l\'indice IRL',
                'category' => 'gestion',
                'default_price' => 170.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 360,
            ],
            [
                'name' => 'Gestion locative mensuelle',
                'description' => 'Vérification des encaissements des loyers & émission des quittances / Relances & suivi des impayés (facturation mensuelle)',
                'category' => 'gestion',
                'default_price' => 5.00,
                'default_tva_rate' => 20,
                'unit' => '%',
                'default_quantity' => 1,
                'sort_order' => 290,
            ],
            [
                'name' => 'Aide à la déclaration fiscale',
                'description' => 'Aide à la déclaration fiscale (2044, LMNP, etc.) - Chaque année',
                'category' => 'gestion',
                'default_price' => 300.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 370,
            ],

            // =====================================
            // SUIVI DES TRAVAUX / MAINTENANCE
            // =====================================
            [
                'name' => 'Commande d\'intervention',
                'description' => 'Contact d\'un artisan pour réparation',
                'category' => 'travaux',
                'default_price' => 70.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 400,
            ],
            [
                'name' => 'Suivi d\'intervention',
                'description' => 'Vérification de la bonne exécution des travaux',
                'category' => 'travaux',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 410,
            ],
            [
                'name' => 'Déclaration de sinistre',
                'description' => 'Constitution du dossier auprès de l\'assurance',
                'category' => 'travaux',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 420,
            ],
            [
                'name' => 'Suivi de sinistre',
                'description' => 'Suivi jusqu\'à indemnisation',
                'category' => 'travaux',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 430,
            ],
            [
                'name' => 'Suivi des gros travaux',
                'description' => 'Coordination et suivi des chantiers importants',
                'category' => 'travaux',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 440,
            ],
            [
                'name' => 'Gestion de devis et choix des prestataires',
                'description' => 'Gestion de devis et choix des prestataires',
                'category' => 'travaux',
                'default_price' => 30.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 390,
            ],
            [
                'name' => 'Supervision des interventions - Travaux < 400€',
                'description' => 'Présence sur site - Forfait travaux inférieurs à 400€ HT',
                'category' => 'travaux',
                'default_price' => 30.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 450,
            ],
            [
                'name' => 'Supervision des interventions - Travaux 400-1000€',
                'description' => 'Présence sur site - Travaux de 400 à 1000€ HT',
                'category' => 'travaux',
                'default_price' => 70.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 460,
            ],
            [
                'name' => 'Supervision des interventions - Travaux > 1000€',
                'description' => 'Présence sur site - Travaux supérieurs à 1000€ HT (6% du montant TTC)',
                'category' => 'travaux',
                'default_price' => 6.00,
                'default_tva_rate' => 20,
                'unit' => '%',
                'default_quantity' => 1,
                'sort_order' => 470,
            ],

            // =====================================
            // AUTRES PRESTATIONS
            // =====================================
            [
                'name' => 'Suivi des attestations d\'assurance locataire',
                'description' => 'Contrôle annuel de validité des contrats',
                'category' => 'autres',
                'default_price' => 50.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 500,
            ],
            [
                'name' => 'Visite annuelle du logement',
                'description' => 'Inspection et rapport d\'état général',
                'category' => 'autres',
                'default_price' => 200.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 510,
            ],
            [
                'name' => 'Assistance juridique bailleur',
                'description' => 'Conseil en cas de litige locatif (minimum 200€)',
                'category' => 'autres',
                'default_price' => 200.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 520,
            ],
            [
                'name' => 'GLI - Assurance Loyers Impayés',
                'description' => 'Garantie Loyers Impayés',
                'category' => 'autres',
                'default_price' => 0.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 530,
            ],
            [
                'name' => 'Rédaction / envoi de préavis ou congés',
                'description' => 'Forfait à part',
                'category' => 'autres',
                'default_price' => 370.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 540,
            ],
            [
                'name' => 'Relance assurance PNO / GRL / loyers impayés',
                'description' => 'Option facultative',
                'category' => 'autres',
                'default_price' => 30.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 550,
            ],
            [
                'name' => 'Audit technique / visite annuelle du bien',
                'description' => 'Recommandé 1 fois/an',
                'category' => 'autres',
                'default_price' => 50.00,
                'default_tva_rate' => 20,
                'unit' => 'forfait',
                'default_quantity' => 1,
                'sort_order' => 560,
            ],
        ];

        foreach ($services as $service) {
            PredefinedService::create($service);
        }
    }
}